### ISSUE TITLE
Can't login to phpmyadmin

### ISSUE THREAD

**Issue by calacianu** [arzek/docker-compose-LAMP-PHP-5.4#2]
Hay man,

I like your project but I have a little problem. I can't login to phpmyadmin. I get those errors:
` mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]`
and
` mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client`

Any ideas on how I can fix this? I changed mysql version to 5, but this gives others issues.

Thanks

**Comment by arzek** [comment]
Hello,
Please see - https://github.com/arzek/docker-compose-LAMP-PHP-5.4/issues/1
